### PR TITLE
grunt api changes

### PR DESCRIPTION
**Pull request by kmmraj**

### CODE REVIEW

**Comment by kmmraj** [comment]
@axemclion Thank for the PR merge , Please publish to npm, waiting to use grunt :-)

**Comment by axemclion** [comment]
@kmmraj I was thinking of adding a `tasks` folder and moving your code in `sampleGruntfile.js` to that task. This way, a user would only have to do `grunt.loadNpmTasks('protractorperf')`, and then do something like

``` javascript
module.exports = function(grunt) {

  grunt.initConfig({
    protractorPerf: {
      options: {
      confileFile : 'conf.js' 
      }
  });

  grunt.loadNpmTasks('protractor-perf');


  grunt.registerTask('default', ['protractorPerf']);

};

```

What do you think ? Thus, protractorPerf still has a command line interface and a node module, but now can be used as a grunt task also.

**Comment by kmmraj** [comment]
Good idea - Can do that, i will send a PR soon.

**Comment by axemclion** [comment]
@kmmraj I published 0.1.7 with the code we have. Once we have the PR, we could publish again !!

**Pull request merged**
