### PR TITLE
Update protractor to 3.0.0

### PR DESCRIPTION
**Pull request by vbardales**

### CODE REVIEW

**Comment by axemclion** [comment]
@vbardales Any reason why we would do a major version bump ?

**Comment by vbardales** [comment]
No reason for major, intermediate is enough :)

**Comment by axemclion** [comment]
@vbardales Can you re-send this pull request with a minor version bump please ? Was there a particular feature that you were looking at getting out ?

**Comment by vbardales** [comment]
done :+1: 

It was impossible for me to install protractor 2.x due to a make file error. But no problem with 3.x version.

**Pull request merged**
